fixes #59 implement Trino adapter
astronomer/astronomer-cosmos pull request #152
Opened 2023-02-17 14:53 UTC by MikeWallis42

fixes #59 

@pohek321, I went a bit crazy and implemented all of the auth types but I'm only able to check ldap.
Can you please double check that you're happy with my implementation of catalog and schema in the context of database_override and schema_override etc.
I could do with a hand on the documentation side of things as well as you've taken lots of screenshots in the other connection docs and I don't want them to be out of theme.

Finally this will be dependant on #134 being merged in as supporting multiple authentication types obviously means lots of optional environment variables that may not get populated.

2023-03-09 19:41 UTC, matthewzahar commented
_patiently waiting for this_

2023-03-17 20:35 UTC, dimberman requested changes

2023-03-17 20:35 UTC, dimberman commented on cosmos/providers/dbt/core/profiles/trino.py
@MikeWallis42  can you please put this in a "dbt/community" directory? Going forward I think we're going to separate the "officially maintained" and "community maintained" profile types.

2023-03-20 20:14 UTC, MikeWallis42 commented on cosmos/providers/dbt/core/profiles/trino.py
@dimberman done, please check you're happy

2023-04-12 19:24 UTC, jlaneve approved these changes

2023-04-12 19:25 UTC, merged