fixes #187 Add support for Exasol dbt adapter
astronomer/astronomer-cosmos pull request #188
Opened 2023-03-16 10:29 UTC by nepux

fixes #187 

Ive quickly added support for the Exasol dbt adapter.
Straight forward implementation with pg implementation as skeleton.

Cheers 🥂

2023-03-17 20:34 UTC, dimberman requested changes

2023-03-17 20:34 UTC, dimberman commented on cosmos/providers/dbt/core/profiles/__init__.py
@nepux can you please put this in a "dbt/community" directory? Going forward I think we're going to separate the "officially maintained" and "community maintained" profile types.

2023-03-21 07:53 UTC, nepux commented on cosmos/providers/dbt/core/profiles/__init__.py
Moved the code into a community folder

2023-04-13 14:57 UTC, nepux commented
Updated the branch and resolved the conflict with the trino adapter.

2023-04-13 15:09 UTC, jlaneve approved these changes

2023-04-13 15:10 UTC, merged